# StaffCore Plugin
# Created by Jayie and Mario.

# Set to false to disable any features.
Features:
  StaffChat: true
  StaffList: true
  ClearChat: true
  MuteChat: true
  Maintenance: true
  Freeze: true
  Vanish: true
  ModMode: true
  Maintenance: true

Errors:
  NoPermission: '&8[&cStaff&8] &cNo Permission.'
  NullPlayer: '&8[&cStaff&8] &cPlayer Does Not Exist.'
  InvalidArgument: '&8[&cStaff&8] &cInvalid Command, use /staff help.'

Database:
  Type: H2
  Address: 'localhost'
  Port: '3306'
  Username: 'root'
  Password: ''
  Database: 'db_staffcore'

StaffChat:
  Prefix: '#'
  Format: '&8[&cStaff&8] &c%player%: &f%message%'
  Sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
  Permission: 'staffcore.staffchat'

StaffList:
  Format:
    - '&8-<>--- &6Staff List &8---<>-'
    - '%list%'
  Permission:
    Staff: 'staffcore.stafflist.staff'
    View: 'staffcore.stafflist.view'

ClearChat:
  Format: '&8[&cStaff&8] &c%player% has cleared the chat.'
  Sound: 'ENTITY_ANVIL_DROP'
  Permission: 'staffcore.clearchat'
  BypassPermission: 'staffcore.clearchat.bypass'

MuteChat:
  Format:
    Mute: '&8[&cStaff&8] &c%player% has muted the chat.'
    Unmute: '&8[&cStaff&8] &a%player% has unmuted the chat.'
  Sound: 'ENTITY_CAT_AMBIENT'
  Permission: 'staffcore.mutechat'

Maintenance:
  Reason: '&c(!) The server is currenlty under maintenance!'
  Format: '&8[&cStaff&8] &c%player% has toggled maintenance mode to %status%.'
  Permission: 'staffcore.maintenance.toggle'
  BypassPermission: 'staffcore.maintenance.bypass'

Freeze:
  Format:
    Player:
      Freeze: '&8[&cStaff&8] &cYou have been frozen by %player%'
      Unfreeze: '&8[&cStaff&8] &cYou have been unfrozen by %player%'
    Moderator:
      Freeze: '&8[&cStaff&8] &cYou have frozen %target%.'
      Unfreeze: '&8[&cStaff&8] &cYou have unfrozen %target%.'
    Permission: 'staffcore.freeze'

Vanish:
  Format:
    Vanish: '&8[&cStaff&8] &aVanish has been toggled on.'
    Unvanish: '&8[&cStaff&8] &cVanish has been toggled off.'
    KeptVanish: '&8[&cStaff&8] &e(!) You are still vanished!' 
  Permission: 'staffcore.vanish'