name: StaffCore
version: '${project.version}'
main: me.jay.staffcore.StaffCore
api-version: 1.18
authors: [ Jayie, Maria ]
description: StaffCore
commands:
  staffchat:
    aliases: [s]
    description: Allows a staff member to chat in the private chat.
